Update upload-artifact action to v4

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,13 +17,21 @@ jobs:
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
-          node-version: 18
+          node-version: 20  # Explicitly specify Node.js 20
 
       - name: Install dependencies
-        uses: bahmutov/npm-install@v1
+        run: npm install
 
       - name: Build project
         run: npm run build
+
+      # Check if the build folder exists before uploading
+      - name: Verify build folder exists
+        run: |
+          if [ ! -d "./dist" ]; then
+            echo "Error: Build folder './dist' does not exist."
+            exit 1
+          fi
 
       - name: Upload production-ready build files
         uses: actions/upload-artifact@v4
